<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	<TargetFramework>net6.0</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\..\src\Optivify.DeviceDetector\Optivify.DeviceDetector.csproj" />
  </ItemGroup>

  <ItemGroup>
	<Content Update="Views\Home\Index.cshtml">
	  <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	</Content>
  </ItemGroup>

</Project>
